//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class actAccCode_Log
    {
        public int LogNo { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogMod { get; set; }
        public string LogModUser { get; set; }
        public Nullable<System.DateTime> LogModDate { get; set; }
        public string LogDataUser { get; set; }
        public Nullable<System.DateTime> LogDataDate { get; set; }
        public Nullable<int> LogMainNo { get; set; }
        public string accTeaCode { get; set; }
        public short accCodeVer { get; set; }
        public string accPlanCode { get; set; }
        public string accOutlayCode { get; set; }
        public string accDepCode { get; set; }
        public string accAccKind { get; set; }
        public string accCodeKind { get; set; }
        public string accCodeType { get; set; }
        public string accMapMainCode { get; set; }
        public string accMapPlanCode { get; set; }
        public string accMapWorkCode { get; set; }
        public string accCheckNo { get; set; }
        public string accAliasNo { get; set; }
        public string accAliasName { get; set; }
        public Nullable<System.DateTime> accCreateDate { get; set; }
        public string accStopFlag { get; set; }
        public Nullable<System.DateTime> accStopDate { get; set; }
        public Nullable<short> accChildCnt { get; set; }
        public string accAbateKind { get; set; }
        public string accMainCode { get; set; }
        public string accMapPlanSubCode { get; set; }
        public string accOutlaySubCode { get; set; }
        public string accPlanSubCode { get; set; }
        public string accWorkCode { get; set; }
    }
}
