//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class actMain_Log
    {
        public int LogNo { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogMod { get; set; }
        public string LogModUser { get; set; }
        public Nullable<System.DateTime> LogModDate { get; set; }
        public string LogDataUser { get; set; }
        public Nullable<System.DateTime> LogDataDate { get; set; }
        public Nullable<int> LogMainNo { get; set; }
        public short acmYear { get; set; }
        public int acmNo { get; set; }
        public string acmKidNum { get; set; }
        public Nullable<short> acmMonth { get; set; }
        public Nullable<short> acmDay { get; set; }
        public string acmBgtKind { get; set; }
        public Nullable<short> acmBgtYear { get; set; }
        public Nullable<short> acmBgtMonth { get; set; }
        public Nullable<int> acmBgtAcmNo { get; set; }
        public string acmBgtUnitNo { get; set; }
        public string acmBgtUnitSubNo { get; set; }
        public string acmWord { get; set; }
        public string acmWordNum { get; set; }
        public Nullable<short> acmWordNumSubNo { get; set; }
        public string acmSourWordNum { get; set; }
        public string acmTopWordNum { get; set; }
        public Nullable<System.DateTime> acmMarkDate { get; set; }
        public string acmTeaCode { get; set; }
        public string acmMarkUnitNo { get; set; }
        public string acmMarkUnitSubNo { get; set; }
        public string acmMarkUserNo { get; set; }
        public string acmWorkUnitNo { get; set; }
        public string acmWorkUnitSubNo { get; set; }
        public string acmWorkUserNo { get; set; }
        public string acmWorkRankNo { get; set; }
        public string acmWorkLevelNo { get; set; }
        public string acmWorkLevelName { get; set; }
        public string acmWorkRankKind { get; set; }
        public string acmWorkLevelKind { get; set; }
        public string acmWorkMapNo { get; set; }
        public Nullable<decimal> acmMoney { get; set; }
        public string acmMemo { get; set; }
        public string acmSubMemo { get; set; }
        public Nullable<short> acmBillCnt { get; set; }
        public string acmRepayKind { get; set; }
        public Nullable<decimal> acmDtlMoney { get; set; }
        public string acmProdLevelKind { get; set; }
        public string acmProdVisaKind { get; set; }
        public string acmProdKind { get; set; }
        public string acmPayName { get; set; }
        public Nullable<decimal> acmPayReMoney { get; set; }
        public string acmPayReMemo { get; set; }
        public Nullable<System.DateTime> acmCreateDTime { get; set; }
        public string acmCreateUser { get; set; }
        public Nullable<System.DateTime> acmModifyDTime { get; set; }
        public string acmModifyUser { get; set; }
        public string acmPassFlag { get; set; }
        public Nullable<System.DateTime> acmPassDate { get; set; }
        public Nullable<System.DateTime> acmPassDTime { get; set; }
        public string acmPassUser { get; set; }
        public string acmFinalKind { get; set; }
        public Nullable<System.DateTime> acmFinalDate { get; set; }
        public string acmSubsidyCode { get; set; }
        public Nullable<decimal> acmPassMoney { get; set; }
        public string acmPassMemo { get; set; }
        public string acmEmpNo { get; set; }
        public string acmAutoBidFlag { get; set; }
        public Nullable<System.DateTime> acmDate { get; set; }
        public string acmUnitPassFlag { get; set; }
        public Nullable<System.DateTime> acmUnitPassDate { get; set; }
        public Nullable<System.DateTime> acmUnitPassDTime { get; set; }
        public string acmUnitPassUser { get; set; }
        public Nullable<decimal> acmUnitPassMoney { get; set; }
        public string acmUnitPassMemo { get; set; }
        public string acmBgtKindSet { get; set; }
        public string acmAutoApplyFlag { get; set; }
        public string acmProcessType { get; set; }
        public string acmActKind { get; set; }
        public string acmAutoPrePayFlag { get; set; }
        public string acmBaseItemsKindCode { get; set; }
        public string acmBatchMemo { get; set; }
        public string acmCateGrpFlag { get; set; }
        public string acmEtcPayment { get; set; }
        public string acmFimPK { get; set; }
        public Nullable<short> acmPayHour { get; set; }
        public string acmPayMethodCode { get; set; }
        public Nullable<System.DateTime> acmPrePayDate { get; set; }
        public string acmProdDepCode { get; set; }
        public string acmProdMethodCode { get; set; }
        public string acmReadyFlag { get; set; }
        public Nullable<System.DateTime> acmRequireDate { get; set; }
        public string acmRequireDepCode { get; set; }
        public string acmRequireUserName { get; set; }
        public string acmReserveFlag { get; set; }
        public string acmReserveWordNum { get; set; }
        public Nullable<System.DateTime> acmReturnDate { get; set; }
        public string acmSelfProdFlag { get; set; }
        public Nullable<System.DateTime> acmUserModifyDTime { get; set; }
        public string acmVisaKindCode { get; set; }
        public Nullable<int> FK_VisaNo { get; set; }
        public string inspect { get; set; }
        public string acmExt { get; set; }
        public string acmOutsideFlag { get; set; }
    }
}
