//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class basPhrase
    {
        public string teaCode { get; set; }
        public short usrNo { get; set; }
        public string phaCode { get; set; }
        public string phaData { get; set; }
        public string phaName { get; set; }
        public string phaGroup { get; set; }
        public string acvAccKind { get; set; }
        public string bizCode { get; set; }
        public string plnCode { get; set; }
        public Nullable<short> codCodeVer { get; set; }
        public string oulCode { get; set; }
        public string phaShareKind { get; set; }
        public string phaEditKind { get; set; }
        public string phaDelKind { get; set; }
        public Nullable<System.DateTime> phaCreateDTime { get; set; }
        public string phaCreateUser { get; set; }
        public Nullable<System.DateTime> phaModifyDTime { get; set; }
        public string phaModifyUser { get; set; }
        public string DepCode { get; set; }
        public string manMainCode { get; set; }
        public string ousOutlaySubCode { get; set; }
        public string wrkCode { get; set; }
    }
}
