//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class basPayName
    {
        public string payCode { get; set; }
        public Nullable<short> payKind { get; set; }
        public string payID { get; set; }
        public string payName { get; set; }
        public string payAliasNo { get; set; }
        public string payTalk1 { get; set; }
        public string payTel1 { get; set; }
        public string payTalk2 { get; set; }
        public string payTel2 { get; set; }
        public string payEMail { get; set; }
        public string payZipCode { get; set; }
        public string payAddress { get; set; }
        public string payShareKind { get; set; }
        public string payEditKind { get; set; }
        public string payDelKind { get; set; }
        public Nullable<short> payCreateUserNo { get; set; }
        public Nullable<System.DateTime> payCreateDTime { get; set; }
        public string payCreateUser { get; set; }
        public Nullable<System.DateTime> payModifyDTime { get; set; }
        public string payModifyUser { get; set; }
        public string payGroup { get; set; }
        public string ranCode { get; set; }
        public string dptCode { get; set; }
        public string dptwCode { get; set; }
        public Nullable<System.DateTime> payStartDT { get; set; }
        public Nullable<System.DateTime> payEndDT { get; set; }
        public string basPassFlag { get; set; }
        public Nullable<System.DateTime> basPassDate { get; set; }
        public string payAlias { get; set; }
        public Nullable<short> payCreateUsrNo { get; set; }
    }
}
