//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgtBudget_Log
    {
        public int LogNo { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogMod { get; set; }
        public string LogModUser { get; set; }
        public Nullable<System.DateTime> LogModDate { get; set; }
        public string LogDataUser { get; set; }
        public Nullable<System.DateTime> LogDataDate { get; set; }
        public Nullable<int> LogMainNo { get; set; }
        public short bgtYear { get; set; }
        public int bgtNo { get; set; }
        public string bgtTeaCode { get; set; }
        public string bgtMarkUnitNo { get; set; }
        public string bgtMarkUnitSubNo { get; set; }
        public string bgtMarkUserNo { get; set; }
        public string bgtDepCode { get; set; }
        public string bgtDptwCode { get; set; }
        public string bgtWorkUnitNo { get; set; }
        public string bgtWorkUnitSubNo { get; set; }
        public Nullable<short> bgtOutlayYear { get; set; }
        public string bgtPlanCode { get; set; }
        public string bgtOutlayCode { get; set; }
        public string bgtBgtSourceCode { get; set; }
        public string bgtAccKind { get; set; }
        public string bgtBizCode { get; set; }
        public string bgtKind { get; set; }
        public string bgtIndepFlag { get; set; }
        public string bgtValKind { get; set; }
        public Nullable<decimal> bgtMoney { get; set; }
        public Nullable<decimal> bgtFreezeMoney { get; set; }
        public Nullable<System.DateTime> bgtDate { get; set; }
        public string bgtMemo { get; set; }
        public string PassFlag { get; set; }
        public Nullable<System.DateTime> PassDTime { get; set; }
        public string PassUser { get; set; }
        public Nullable<int> bgsNo { get; set; }
        public Nullable<System.DateTime> CreateDTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyDTime { get; set; }
        public string ModifyUser { get; set; }
        public string bgtGbaFlag { get; set; }
        public Nullable<short> acmYear { get; set; }
        public Nullable<int> acmNo { get; set; }
        public string bgtBidFlag { get; set; }
        public Nullable<short> acmNo1 { get; set; }
        public Nullable<short> acmNo2 { get; set; }
        public string bgtSubKind { get; set; }
        public string bgtKindSet { get; set; }
        public Nullable<int> acmNoPrv { get; set; }
        public Nullable<short> acvNo { get; set; }
        public Nullable<short> acvNo1 { get; set; }
        public Nullable<short> acvNo2 { get; set; }
        public string bgtMainCode { get; set; }
        public string bgtOutlaySubCode { get; set; }
        public string bgtPlanCateCode { get; set; }
        public string bgtWorkCode { get; set; }
        public string bgtPlanCodePN { get; set; }
        public string bgtOutlayCodePN { get; set; }
        public string bgtFromLastYear { get; set; }
    }
}
