//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgtBudgetSet
    {
        public short bgsYear { get; set; }
        public int bgsNo { get; set; }
        public Nullable<System.DateTime> bgsDate { get; set; }
        public string bgsTeaCode { get; set; }
        public string bgsMarkUnitNo { get; set; }
        public string bgsMarkUnitSubNo { get; set; }
        public string bgsMarkUserNo { get; set; }
        public Nullable<short> bgsOutlayYear { get; set; }
        public string bgsBgtSourceCode { get; set; }
        public string bgsKind { get; set; }
        public string bgsValKind { get; set; }
        public Nullable<decimal> bgsTotal { get; set; }
        public string bgsMemo { get; set; }
        public Nullable<int> bgmNo { get; set; }
        public string bgsRateFlag { get; set; }
        public string bgsEditName { get; set; }
        public Nullable<System.DateTime> bgsEditDtime { get; set; }
        public Nullable<short> acmYear { get; set; }
        public Nullable<int> acmNo { get; set; }
        public string bgsBidFlag { get; set; }
        public Nullable<short> acmNo1 { get; set; }
        public Nullable<short> acmNo2 { get; set; }
        public string bgsSubKind { get; set; }
        public Nullable<int> acmNoPrv { get; set; }
        public Nullable<short> acvNo { get; set; }
        public Nullable<short> acvNo1 { get; set; }
        public Nullable<short> acvNo2 { get; set; }
    }
}
