//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGSSLogDistinct
    {
        public string CustomID { get; set; }
        public Nullable<System.DateTime> UploadDateTime { get; set; }
        public string UploadData { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusSearchDateTime { get; set; }
        public string UploadID { get; set; }
        public string UpLoadSuccessful { get; set; }
        public string UploadErrorMessage { get; set; }
        public string Action { get; set; }
        public string UploadDeleteData { get; set; }
    }
}
