//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class chkActBgtCode_Log
    {
        public int LogNo { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogMod { get; set; }
        public string LogModUser { get; set; }
        public Nullable<System.DateTime> LogModDate { get; set; }
        public string LogDataUser { get; set; }
        public Nullable<System.DateTime> LogDataDate { get; set; }
        public Nullable<int> LogMainNo { get; set; }
        public short codCodeVer { get; set; }
        public int chsNo { get; set; }
        public int chkNo { get; set; }
        public string chkSourKind { get; set; }
        public string chkAimKind { get; set; }
        public string chkActStage { get; set; }
        public string chkSaveFlag { get; set; }
        public string chkMsgType { get; set; }
        public string chkTeaCode { get; set; }
        public string chkBgtUnitNo { get; set; }
        public string chkWorkUnitNo { get; set; }
        public string chkWorkUserName { get; set; }
        public string chkEmpNo { get; set; }
        public string chkAccKind { get; set; }
        public string chkBgtSourCode { get; set; }
        public string chkBgtDepCode { get; set; }
        public Nullable<short> chkOulYear { get; set; }
        public string chkBizCode { get; set; }
        public string chkPlanCode { get; set; }
        public string chkOulCode { get; set; }
        public string chkPlanCodePN { get; set; }
        public string chkOulCodePN { get; set; }
        public Nullable<short> chkPercent { get; set; }
        public Nullable<decimal> chkMoney { get; set; }
        public Nullable<short> chkGroupNo { get; set; }
        public string chkMoneyKind { get; set; }
        public string chkDataKind { get; set; }
        public string chkDateKind { get; set; }
        public string acmProdLevelKind { get; set; }
        public string acmProdVisaKind { get; set; }
        public string acmProdKind { get; set; }
        public string chkAutoSaveFlag { get; set; }
    }
}
