//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class codBizName
    {
        public short codCodeVer { get; set; }
        public string BizCode { get; set; }
        public string BizName { get; set; }
        public string bizAliasNo { get; set; }
        public string bizAliasName { get; set; }
        public Nullable<System.DateTime> bizCreateDate { get; set; }
        public string bizStopFlag { get; set; }
        public Nullable<System.DateTime> bizStopDate { get; set; }
    }
}
