//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class codDepartName
    {
        public string dptCode { get; set; }
        public string dptName { get; set; }
        public string dptLevel { get; set; }
        public string dptBgtFlag { get; set; }
        public string dptWorkFlag { get; set; }
        public string depCtrlAllFlag { get; set; }
        public string dptTeamFlag { get; set; }
        public string teaCode { get; set; }
        public string dptAliasNo { get; set; }
        public string dptAliasName { get; set; }
        public Nullable<System.DateTime> dptCreateDate { get; set; }
        public string dptStopFlag { get; set; }
        public Nullable<System.DateTime> dptStopDate { get; set; }
        public string ageAgentNo { get; set; }
        public short dptYear { get; set; }
        public Nullable<short> dptChildCnt { get; set; }
        public string dptFax { get; set; }
        public Nullable<int> dptOrderNo { get; set; }
        public string dptParentCode { get; set; }
        public string dptTel { get; set; }
    }
}
