//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class codOutlayCode_Log
    {
        public int LogNo { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogMod { get; set; }
        public string LogModUser { get; set; }
        public Nullable<System.DateTime> LogModDate { get; set; }
        public string LogDataUser { get; set; }
        public Nullable<System.DateTime> LogDataDate { get; set; }
        public Nullable<int> LogMainNo { get; set; }
        public short codCodeVer { get; set; }
        public string oulOutlayCode { get; set; }
        public string oulOutlayName { get; set; }
        public Nullable<short> oulLevel { get; set; }
        public Nullable<short> oulLevelEnd { get; set; }
        public string oulAccKind { get; set; }
        public string oulCodeKind { get; set; }
        public string oulCodeFinal { get; set; }
        public string oulMapMainCode { get; set; }
        public string oulMapPlanCode { get; set; }
        public string oulMapWorkCode { get; set; }
        public string oulCheckNo { get; set; }
        public string oulAliasNo { get; set; }
        public string oulAliasName { get; set; }
        public Nullable<System.DateTime> oulCreateDate { get; set; }
        public string oulStopFlag { get; set; }
        public Nullable<System.DateTime> oulStopDate { get; set; }
        public Nullable<short> oulChildCnt { get; set; }
        public string oulAbateKind { get; set; }
        public string oulCategory { get; set; }
    }
}
