//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class codPlanCode
    {
        public short codCodeVer { get; set; }
        public string plnPlanCode { get; set; }
        public string plnPlanName { get; set; }
        public Nullable<short> plnLevel { get; set; }
        public Nullable<short> plnLevelEnd { get; set; }
        public Nullable<System.DateTime> plnCreateDate { get; set; }
        public string plnStopFlag { get; set; }
        public Nullable<System.DateTime> plnStopDate { get; set; }
        public string plnAliasNo { get; set; }
        public string plnAliasNo1 { get; set; }
        public string plnAliasNo2 { get; set; }
        public string plnAliasNo3 { get; set; }
        public string plnAliasName { get; set; }
        public string plnCodeSide { get; set; }
        public string plnAccKind { get; set; }
        public string plnCodeKind { get; set; }
        public string plnCodeType { get; set; }
        public string plnCodeFinal { get; set; }
        public string plnCheckNo { get; set; }
        public string plnAbatedKind { get; set; }
        public string plnAbateKind { get; set; }
        public Nullable<int> plnChildCnt { get; set; }
        public string plnCategory { get; set; }
        public string plnCreateDpt { get; set; }
        public string plnExpeMemo { get; set; }
        public string plnPlanMemo { get; set; }
        public string plnWorker { get; set; }
    }
}
