//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class codSubsidyCatName
    {
        public short codCodeVer { get; set; }
        public string SubCatCode { get; set; }
        public string SubCatName { get; set; }
        public string SubCatLevel { get; set; }
        public string SubStopFlag { get; set; }
    }
}
