//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class codSysPara
    {
        public string cspCode { get; set; }
        public string cspName { get; set; }
        public string cspValue { get; set; }
        public string cspMemo { get; set; }
        public string cspStopFlag { get; set; }
        public Nullable<System.DateTime> cspCreateDTime { get; set; }
        public string cspCreateUser { get; set; }
        public Nullable<System.DateTime> cspModifyDTime { get; set; }
        public string cspModifyUser { get; set; }
        public string cspShowFlag { get; set; }
    }
}
