//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class codTrlMember
    {
        public short tsbYear { get; set; }
        public int tsbTrlRptNo { get; set; }
        public short tsbPayYear { get; set; }
        public int tsbPayNo { get; set; }
        public string ctmUserName { get; set; }
        public string ctmUnitName { get; set; }
        public string ctmUserTitle { get; set; }
        public string ctmDelegateFlag { get; set; }
        public Nullable<System.DateTime> ctmModifyDTime { get; set; }
        public string ctmModifyUser { get; set; }
    }
}
