//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class codTeamName_Log
    {
        public int LogNo { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogMod { get; set; }
        public string LogModUser { get; set; }
        public Nullable<System.DateTime> LogModDate { get; set; }
        public string LogDataUser { get; set; }
        public Nullable<System.DateTime> LogDataDate { get; set; }
        public Nullable<int> LogMainNo { get; set; }
        public string teaCode { get; set; }
        public string teaName { get; set; }
        public Nullable<short> teaLevel { get; set; }
        public string teaKind { get; set; }
        public string teaAllFlag { get; set; }
        public string teaDptCode { get; set; }
        public string teaAliasNo { get; set; }
        public string teaAliasName { get; set; }
        public Nullable<System.DateTime> teaCreateDate { get; set; }
        public string teaStopFlag { get; set; }
        public Nullable<System.DateTime> teaStopDate { get; set; }
        public string ageAgentNo { get; set; }
    }
}
