//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebsAgent_Log
    {
        public int LogNo { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogMod { get; set; }
        public string LogModUser { get; set; }
        public Nullable<System.DateTime> LogModDate { get; set; }
        public string LogDataUser { get; set; }
        public Nullable<System.DateTime> LogDataDate { get; set; }
        public Nullable<int> LogMainNo { get; set; }
        public string ageAgentNo { get; set; }
        public string ageAgentName { get; set; }
        public string ageAgentTel { get; set; }
        public string ageAgentAddr { get; set; }
        public string ageAgentAdm { get; set; }
        public string ageAgentType { get; set; }
        public string ageCityName { get; set; }
        public string ageMarkName { get; set; }
        public string ageSysName { get; set; }
        public string ageSysKind { get; set; }
        public string ageAccAdmName { get; set; }
        public string ageUserName { get; set; }
        public string ageUserTel { get; set; }
        public string ageUserEmail { get; set; }
        public string ageAgentOrderNo { get; set; }
        public Nullable<System.DateTime> ageCreateDate { get; set; }
        public string ageStopFlag { get; set; }
        public Nullable<System.DateTime> ageStopDate { get; set; }
        public string ageAccDBName { get; set; }
        public string ageAccDBUserID { get; set; }
        public string ageAccDBPass { get; set; }
        public string ageAccDBIP { get; set; }
    }
}
