//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOHWFGBCEEntities : DbContext
    {
        public MOHWFGBCEEntities()
            : base("name=MOHWFGBCEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<actAccCode> actAccCode { get; set; }
        public DbSet<actAccCode_Log> actAccCode_Log { get; set; }
        public DbSet<actMain> actMain { get; set; }
        public DbSet<actMain_Log> actMain_Log { get; set; }
        public DbSet<basBaseData> basBaseData { get; set; }
        public DbSet<basBaseData_Log> basBaseData_Log { get; set; }
        public DbSet<basPayName> basPayName { get; set; }
        public DbSet<basPayName_Log> basPayName_Log { get; set; }
        public DbSet<basPhrase> basPhrase { get; set; }
        public DbSet<basPhrase_Log> basPhrase_Log { get; set; }
        public DbSet<bgtBudget> bgtBudget { get; set; }
        public DbSet<bgtBudget_Log> bgtBudget_Log { get; set; }
        public DbSet<bgtBudgetSet> bgtBudgetSet { get; set; }
        public DbSet<bgtBudgetSet_Log> bgtBudgetSet_Log { get; set; }
        public DbSet<bgtMonth> bgtMonth { get; set; }
        public DbSet<bgtMonth_Log> bgtMonth_Log { get; set; }
        public DbSet<CGSSLogDistinct> CGSSLogDistinct { get; set; }
        public DbSet<chkActBgtCode> chkActBgtCode { get; set; }
        public DbSet<chkActBgtCode_Log> chkActBgtCode_Log { get; set; }
        public DbSet<chkActPlanRole> chkActPlanRole { get; set; }
        public DbSet<codAccKindName> codAccKindName { get; set; }
        public DbSet<codAccKindName_Log> codAccKindName_Log { get; set; }
        public DbSet<codBgtOrigin> codBgtOrigin { get; set; }
        public DbSet<codBizName> codBizName { get; set; }
        public DbSet<codBizName_Log> codBizName_Log { get; set; }
        public DbSet<codDepartName> codDepartName { get; set; }
        public DbSet<codDepartName_Log> codDepartName_Log { get; set; }
        public DbSet<codDepBiz> codDepBiz { get; set; }
        public DbSet<codDepBiz_Log> codDepBiz_Log { get; set; }
        public DbSet<codOutlayCode> codOutlayCode { get; set; }
        public DbSet<codOutlayCode_Log> codOutlayCode_Log { get; set; }
        public DbSet<codOutlayCodePN> codOutlayCodePN { get; set; }
        public DbSet<codOutlayCodePN_Log> codOutlayCodePN_Log { get; set; }
        public DbSet<codPlanCategory> codPlanCategory { get; set; }
        public DbSet<codPlanCategory_Log> codPlanCategory_Log { get; set; }
        public DbSet<codPlanCode> codPlanCode { get; set; }
        public DbSet<codPlanCode_Log> codPlanCode_Log { get; set; }
        public DbSet<codPlanCodePN> codPlanCodePN { get; set; }
        public DbSet<codPlanCodePN_Log> codPlanCodePN_Log { get; set; }
        public DbSet<codSubsidyCatName> codSubsidyCatName { get; set; }
        public DbSet<codSubsidyOutlayRole> codSubsidyOutlayRole { get; set; }
        public DbSet<codSysPara> codSysPara { get; set; }
        public DbSet<codTeamName> codTeamName { get; set; }
        public DbSet<codTeamName_Log> codTeamName_Log { get; set; }
        public DbSet<codTrlMember> codTrlMember { get; set; }
        public DbSet<ebsAgent_Log> ebsAgent_Log { get; set; }
        public DbSet<logWhoRec> logWhoRec { get; set; }
        public DbSet<sysBaseUser> sysBaseUser { get; set; }
        public DbSet<sysBaseUser_Log> sysBaseUser_Log { get; set; }
        public DbSet<sysGroupData> sysGroupData { get; set; }
        public DbSet<sysGroupData_Log> sysGroupData_Log { get; set; }
        public DbSet<sysGroupName> sysGroupName { get; set; }
        public DbSet<sysGroupName_Log> sysGroupName_Log { get; set; }
        public DbSet<sysMenuBase> sysMenuBase { get; set; }
        public DbSet<sysMenuBase_Log> sysMenuBase_Log { get; set; }
        public DbSet<sysUserPower> sysUserPower { get; set; }
        public DbSet<sysUserPower_Log> sysUserPower_Log { get; set; }
        public DbSet<tsbApply> tsbApply { get; set; }
        public DbSet<tsbApply_Log> tsbApply_Log { get; set; }
        public DbSet<tsbApplyDtl> tsbApplyDtl { get; set; }
        public DbSet<tsbApplyDtl_Log> tsbApplyDtl_Log { get; set; }
        public DbSet<tsbCity> tsbCity { get; set; }
        public DbSet<tsbCityArea> tsbCityArea { get; set; }
        public DbSet<tsbDecide> tsbDecide { get; set; }
        public DbSet<tsbDecide_Log> tsbDecide_Log { get; set; }
        public DbSet<tsbDecideDtl> tsbDecideDtl { get; set; }
        public DbSet<tsbDecideDtl_Log> tsbDecideDtl_Log { get; set; }
        public DbSet<tsbEstimate> tsbEstimate { get; set; }
        public DbSet<tsbEstimate_Log> tsbEstimate_Log { get; set; }
        public DbSet<tsbEstimateOverAgainst> tsbEstimateOverAgainst { get; set; }
        public DbSet<tsbEstimateOverAgainst_Log> tsbEstimateOverAgainst_Log { get; set; }
        public DbSet<tsbEstimateTranBatch> tsbEstimateTranBatch { get; set; }
        public DbSet<tsbEstimateTranBatchDtl> tsbEstimateTranBatchDtl { get; set; }
        public DbSet<tsbFee> tsbFee { get; set; }
        public DbSet<tsbFeePlanCode> tsbFeePlanCode { get; set; }
        public DbSet<tsbInspect> tsbInspect { get; set; }
        public DbSet<tsbInterestData> tsbInterestData { get; set; }
        public DbSet<tsbMemo> tsbMemo { get; set; }
        public DbSet<tsbMHWAnnualRptFinal> tsbMHWAnnualRptFinal { get; set; }
        public DbSet<tsbMHWAnnualRptImport> tsbMHWAnnualRptImport { get; set; }
        public DbSet<tsbMHWEstImport> tsbMHWEstImport { get; set; }
        public DbSet<tsbMHWMonthlyRptImport> tsbMHWMonthlyRptImport { get; set; }
        public DbSet<tsbMHWSeasonRptImport> tsbMHWSeasonRptImport { get; set; }
        public DbSet<tsbOpenEstimateSetting> tsbOpenEstimateSetting { get; set; }
        public DbSet<tsbPay> tsbPay { get; set; }
        public DbSet<tsbPay_Log> tsbPay_Log { get; set; }
        public DbSet<tsbPayDtl> tsbPayDtl { get; set; }
        public DbSet<tsbPayDtl_Log> tsbPayDtl_Log { get; set; }
        public DbSet<tsbPayee> tsbPayee { get; set; }
        public DbSet<tsbPayee1> tsbPayee1 { get; set; }
        public DbSet<tsbPayeeGroupData> tsbPayeeGroupData { get; set; }
        public DbSet<tsbPayeeGroupName> tsbPayeeGroupName { get; set; }
        public DbSet<tsbPayeePayee1REL> tsbPayeePayee1REL { get; set; }
        public DbSet<tsbPayeeProperty> tsbPayeeProperty { get; set; }
        public DbSet<tsbPayeeRole> tsbPayeeRole { get; set; }
        public DbSet<tsbPayOffset> tsbPayOffset { get; set; }
        public DbSet<tsbPrePay> tsbPrePay { get; set; }
        public DbSet<tsbPrePay_Log> tsbPrePay_Log { get; set; }
        public DbSet<tsbPrePayDtl> tsbPrePayDtl { get; set; }
        public DbSet<tsbPrePayDtl_Log> tsbPrePayDtl_Log { get; set; }
        public DbSet<tsbReceipt> tsbReceipt { get; set; }
        public DbSet<tsbReceipt_Log> tsbReceipt_Log { get; set; }
        public DbSet<tsbRptInputDataDtl> tsbRptInputDataDtl { get; set; }
        public DbSet<tsbRptInputDataM> tsbRptInputDataM { get; set; }
        public DbSet<tsbTransfer> tsbTransfer { get; set; }
        public DbSet<tsbTrlReportInput> tsbTrlReportInput { get; set; }
        public DbSet<tsbUnfinishCause> tsbUnfinishCause { get; set; }
        public DbSet<Acc_01_dbo_Y104_VisaNewMainNo> Acc_01_dbo_Y104_VisaNewMainNo { get; set; }
        public DbSet<codFD_BaseMenu> codFD_BaseMenu { get; set; }
        public DbSet<codFormulaDesc> codFormulaDesc { get; set; }
        public DbSet<codKind> codKind { get; set; }
        public DbSet<ebsAgent> ebsAgent { get; set; }
        public DbSet<tsbficEntrustFiles> tsbficEntrustFiles { get; set; }
        public DbSet<tsbMemo_tsbYear_tsbMemoNo_Inc> tsbMemo_tsbYear_tsbMemoNo_Inc { get; set; }
        public DbSet<tsbMHWAnnualRptFinal_tsbYear_tsbMHWAnRptFinalNo_Inc> tsbMHWAnnualRptFinal_tsbYear_tsbMHWAnRptFinalNo_Inc { get; set; }
        public DbSet<GBCVisaDetail> GBCVisaDetail { get; set; }
        public DbSet<vw_GBCVisaDetailWithAbate> vw_GBCVisaDetailWithAbate { get; set; }
    }
}
