//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class logWhoRec
    {
        public int LogNo { get; set; }
        public string LogIP { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogUser { get; set; }
        public string LogMod { get; set; }
        public string LogPage { get; set; }
        public string LogWork { get; set; }
        public string LogMemo { get; set; }
        public string LogWorkUser { get; set; }
        public Nullable<short> LogLevel { get; set; }
        public string LogLink { get; set; }
        public string LogSys { get; set; }
    }
}
