//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysGroupName_Log
    {
        public int LogNo { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogMod { get; set; }
        public string LogModUser { get; set; }
        public Nullable<System.DateTime> LogModDate { get; set; }
        public string LogDataUser { get; set; }
        public Nullable<System.DateTime> LogDataDate { get; set; }
        public Nullable<int> LogMainNo { get; set; }
        public short PK_grpNo { get; set; }
        public string grpName { get; set; }
        public string grpEditName { get; set; }
        public Nullable<System.DateTime> grpEditDTime { get; set; }
        public string grpAdd { get; set; }
        public string grpDel { get; set; }
        public Nullable<short> grpLevel { get; set; }
        public string grpMode { get; set; }
        public string grpModify { get; set; }
        public string grpPower1 { get; set; }
        public string grpPower2 { get; set; }
        public string grpPower3 { get; set; }
        public string grpPower4 { get; set; }
        public string grpPrn { get; set; }
        public string grpSeek { get; set; }
    }
}
