//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsbApply
    {
        public tsbApply()
        {
            this.tsbApplyDtl = new HashSet<tsbApplyDtl>();
            this.tsbDecide = new HashSet<tsbDecide>();
        }
    
        public short tsbYear { get; set; }
        public int tsbApplyNo { get; set; }
        public string tsbKindNum { get; set; }
        public Nullable<short> tsbTSBYear { get; set; }
        public string tsbTrustSubsidyName { get; set; }
        public string tsbPlanCode { get; set; }
        public Nullable<short> tsbBgtYear { get; set; }
        public Nullable<short> tsbBgtMonth { get; set; }
        public string tsbBgtUnitNo { get; set; }
        public string tsbApplyWordNum { get; set; }
        public string tsbLastApplyWordNum { get; set; }
        public Nullable<System.DateTime> tsbMarkDate { get; set; }
        public string tsbMarkUnitNo { get; set; }
        public string tsbMarkUserNo { get; set; }
        public string tsbWorkUnitNo { get; set; }
        public string tsbWorkUserNo { get; set; }
        public Nullable<decimal> tsbMoney { get; set; }
        public string tsbMemo { get; set; }
        public string tsbSubMemo { get; set; }
        public Nullable<System.DateTime> tsbCreateDTime { get; set; }
        public string tsbCreateUser { get; set; }
        public Nullable<System.DateTime> tsbModifyDTime { get; set; }
        public string tsbModifyUser { get; set; }
        public string tsbPassFlag { get; set; }
        public Nullable<System.DateTime> tsbPassDTime { get; set; }
        public string tsbPassUser { get; set; }
        public string IsTransfer { get; set; }
        public string IsInterest { get; set; }
    
        public virtual ICollection<tsbApplyDtl> tsbApplyDtl { get; set; }
        public virtual ICollection<tsbDecide> tsbDecide { get; set; }
    }
}
