//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsbInspect
    {
        public short tsbYear { get; set; }
        public int tsbApplyNo { get; set; }
        public int tsbApplySeq { get; set; }
        public int tsbDecideNo { get; set; }
        public short tsbDecideSeq { get; set; }
        public string tsbApplyWordNum { get; set; }
        public string tsbBgtKind { get; set; }
        public Nullable<short> tsbBgtYear { get; set; }
        public Nullable<short> tsbBgtMonth { get; set; }
        public string tsbPayeeNo { get; set; }
        public string tsbPayeeName { get; set; }
        public string tsbPlanCode { get; set; }
        public Nullable<short> tsbOutlayYear { get; set; }
        public string tsbOutlayCode { get; set; }
        public string tsbBgtSourceCode { get; set; }
        public string tsbAccKind { get; set; }
        public string tsbBizCode { get; set; }
        public string tsbBgtDepCode { get; set; }
        public Nullable<decimal> tsbMoney { get; set; }
        public Nullable<decimal> tsbMoney1 { get; set; }
        public string tsbAuditFlag { get; set; }
        public Nullable<System.DateTime> tsbAuditDate { get; set; }
        public string tsbAuditUser { get; set; }
        public Nullable<System.DateTime> tsbCreateDTime { get; set; }
        public string tsbCreateUser { get; set; }
        public Nullable<System.DateTime> tsbModifyDTime { get; set; }
        public string tsbModifyUser { get; set; }
        public string tsbInspectNum { get; set; }
        public string tsbCauseFlag1 { get; set; }
        public string tsbCauseFlag2 { get; set; }
        public string tsbCauseFlag3 { get; set; }
        public string tsbCauseFlag4 { get; set; }
        public string tsbOtherCause { get; set; }
        public Nullable<decimal> tsbInspectMoney { get; set; }
        public string tsbInspectKind { get; set; }
        public string tsbInstitutionName { get; set; }
        public string tsbNoBigMissFlag { get; set; }
    }
}
