//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsbMHWEstImport
    {
        public short tsbYear { get; set; }
        public int tsbMHWEstImportNo { get; set; }
        public int tsbApplyNo { get; set; }
        public int tsbApplySeq { get; set; }
        public int tsbDecideNo { get; set; }
        public short tsbDecideSeq { get; set; }
        public string tsbPayeeNo { get; set; }
        public string tsbPayeeName { get; set; }
        public string tsbPlanCode { get; set; }
        public Nullable<short> tsbOutlayYear { get; set; }
        public string tsbOutlayCode { get; set; }
        public Nullable<decimal> tsbEstimateMoney { get; set; }
        public Nullable<decimal> tsbPreMoney { get; set; }
        public Nullable<System.DateTime> tsbEstimateDate { get; set; }
        public Nullable<System.DateTime> tsbCreateDTime { get; set; }
        public string tsbCreateUser { get; set; }
        public string tsbEstimateType { get; set; }
        public string tsbChildPayeeNo { get; set; }
        public string tsbChildPayeeName { get; set; }
        public string tsbCityID { get; set; }
        public string tsbCityName { get; set; }
        public string tsbCityAreaNo { get; set; }
        public string tsbCityAreaName { get; set; }
        public string tsbPayeeRoleNo { get; set; }
        public string tsbPayeeRoleName { get; set; }
        public string tsbPayeePropertyNo { get; set; }
        public string tsbPayeePropertyName { get; set; }
    }
}
