//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsbMHWSeasonRptImport
    {
        public short tsbYear { get; set; }
        public int tsbMHWSeaImpNo { get; set; }
        public int tsbApplyNo { get; set; }
        public int tsbDecideNo { get; set; }
        public int tsbApplySeq { get; set; }
        public short tsbDecideSeq { get; set; }
        public string tsbPayeeNo { get; set; }
        public string tsbPayeeName { get; set; }
        public string tsbPlanCode { get; set; }
        public Nullable<short> tsbOutlayYear { get; set; }
        public string tsbOutlayCode { get; set; }
        public string tsbBgtSourceCode { get; set; }
        public string tsbAccKind { get; set; }
        public string tsbBizCode { get; set; }
        public string tsbChildPayeeNo { get; set; }
        public string tsbChildPayeeName { get; set; }
        public Nullable<System.DateTime> tsbImportDate { get; set; }
        public Nullable<decimal> tsbDecideMoney { get; set; }
        public Nullable<decimal> tsbOtherNum { get; set; }
        public Nullable<decimal> tsbSelfNum { get; set; }
        public Nullable<decimal> tsbSeasonPayMoney { get; set; }
        public Nullable<decimal> tsbSeasonPayMoneyTot { get; set; }
        public string tsbShareOrgName { get; set; }
        public string tsbCityID { get; set; }
        public string tsbCityName { get; set; }
        public string tsbCityAreaNo { get; set; }
        public string tsbCityAreaName { get; set; }
        public string tsbPayeeRoleNo { get; set; }
        public string tsbPayeeRoleName { get; set; }
        public string tsbPayeePropertyNo { get; set; }
        public string tsbPayeePropertyName { get; set; }
        public Nullable<int> tsbImportSeason { get; set; }
    }
}
