//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsbPayOffset
    {
        public short tsbYear { get; set; }
        public int tsbApplyNo { get; set; }
        public int tsbDecideNo { get; set; }
        public short tsbPayYear { get; set; }
        public int tsbPayNo { get; set; }
        public int tsbApplySeq { get; set; }
        public short tsbDecideSeq { get; set; }
        public int tsbEstimateNo { get; set; }
        public int tsbPrePayNo { get; set; }
        public short tsbPrePayYear { get; set; }
        public string tsbPayeeNo { get; set; }
        public string tsbPayeeName { get; set; }
        public string tsbPlanCode { get; set; }
        public Nullable<short> tsbOutlayYear { get; set; }
        public string tsbOutlayCode { get; set; }
        public string tsbBgtSourceCode { get; set; }
        public string tsbAccKind { get; set; }
        public string tsbBizCode { get; set; }
        public Nullable<decimal> tsbEstimateMoney { get; set; }
        public Nullable<decimal> tsbPreMoney { get; set; }
        public int tsbApplyNoEst { get; set; }
        public int tsbApplySeqEst { get; set; }
        public int tsbDecideNoEst { get; set; }
        public short tsbDecideSeqEst { get; set; }
        public int tsbApplyNoPre { get; set; }
        public int tsbApplySeqPre { get; set; }
        public int tsbDecideNoPre { get; set; }
        public short tsbDecideSeqPre { get; set; }
    }
}
