//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsbPayeePayee1REL
    {
        public string tsbPayeeNo { get; set; }
        public string tsbPayeeNo1 { get; set; }
    
        public virtual tsbPayee1 tsbPayee1 { get; set; }
    }
}
