//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsbPayee1
    {
        public tsbPayee1()
        {
            this.tsbPayeePayee1REL = new HashSet<tsbPayeePayee1REL>();
        }
    
        public string tsbPayeeNo1 { get; set; }
        public Nullable<short> tsbYear { get; set; }
        public string tsbPayeeName { get; set; }
        public string tsbPayeeRoleNo { get; set; }
        public string tsbPayeePropertyNo { get; set; }
        public string tsbCityID { get; set; }
        public string tsbCityAreaNo { get; set; }
        public string tsbPayeeKind { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string StopFlag { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
    
        public virtual tsbCityArea tsbCityArea { get; set; }
        public virtual tsbPayeeProperty tsbPayeeProperty { get; set; }
        public virtual tsbPayeeRole tsbPayeeRole { get; set; }
        public virtual ICollection<tsbPayeePayee1REL> tsbPayeePayee1REL { get; set; }
    }
}
