//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsbRptInputDataM
    {
        public tsbRptInputDataM()
        {
            this.tsbRptInputDataDtl = new HashSet<tsbRptInputDataDtl>();
        }
    
        public short tsbYear { get; set; }
        public int tsbApplyNo { get; set; }
        public int tsbApplySeq { get; set; }
        public int tsbDecideNo { get; set; }
        public short tsbDecideSeq { get; set; }
        public Nullable<decimal> tsbOtherNumTot { get; set; }
        public Nullable<decimal> tsbSelfNum { get; set; }
        public Nullable<System.DateTime> tsbPeriodStart { get; set; }
        public Nullable<System.DateTime> tsbPeriodEnd { get; set; }
        public Nullable<System.DateTime> tsbExpFinishDate { get; set; }
        public Nullable<System.DateTime> tsbRealFinishDate { get; set; }
        public Nullable<System.DateTime> tsbStartDate { get; set; }
        public Nullable<System.DateTime> tsbEndDate { get; set; }
        public Nullable<decimal> tsbApplicationMoney { get; set; }
        public Nullable<decimal> UnitAmount { get; set; }
        public Nullable<decimal> SelfAmount { get; set; }
        public Nullable<decimal> ExtAmount { get; set; }
        public string AppliedRemark { get; set; }
        public string ExtRemark { get; set; }
        public string Contact { get; set; }
    
        public virtual tsbDecideDtl tsbDecideDtl { get; set; }
        public virtual ICollection<tsbRptInputDataDtl> tsbRptInputDataDtl { get; set; }
    }
}
