//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsbRptInputDataDtl
    {
        public short tsbYear { get; set; }
        public int tsbApplyNo { get; set; }
        public int tsbApplySeq { get; set; }
        public int tsbDecideNo { get; set; }
        public short tsbDecideSeq { get; set; }
        public string tsbShareOrgName { get; set; }
        public Nullable<decimal> tsbOtherNum { get; set; }
    
        public virtual tsbRptInputDataM tsbRptInputDataM { get; set; }
    }
}
