//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsbTrlReportInput
    {
        public short tsbYear { get; set; }
        public int tsbTrlRptNo { get; set; }
        public Nullable<int> tsbApplyNo { get; set; }
        public Nullable<int> tsbApplySeq { get; set; }
        public Nullable<int> tsbDecideNo { get; set; }
        public Nullable<short> tsbDecideSeq { get; set; }
        public string tsbTrlPlanName { get; set; }
        public string codTrlKindCode { get; set; }
        public string tsbTrlCountry { get; set; }
        public string tsbTrlCity { get; set; }
        public Nullable<System.DateTime> tsbTrlSDate { get; set; }
        public Nullable<System.DateTime> tsbTrlEDate { get; set; }
        public Nullable<System.DateTime> tsbCreateDTime { get; set; }
        public string tsbCreateUser { get; set; }
        public Nullable<System.DateTime> tsbModifyDTime { get; set; }
        public string tsbModifyUser { get; set; }
        public string tsbTrlBgtSource { get; set; }
        public string tsbTrlSourceName { get; set; }
        public Nullable<System.DateTime> tsbTrlRPTDate { get; set; }
        public string tsbTrlContent { get; set; }
        public Nullable<short> tsbTrlRecomItem { get; set; }
        public Nullable<short> tsbTrlAdoptionItem { get; set; }
        public Nullable<short> tsbTrlNoAdoptionItem { get; set; }
        public Nullable<short> tsbTrlDiscussItem { get; set; }
        public string tsbTrlMemo { get; set; }
        public string tsbTrlPlanNameOri { get; set; }
    }
}
