//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsbTransfer
    {
        public short tsbNewYear { get; set; }
        public int tsbNewApplyNo { get; set; }
        public int tsbNewApplySeq { get; set; }
        public int tsbNewDecideNo { get; set; }
        public short tsbNewDecideSeq { get; set; }
        public string tsbNewApplyWordNum { get; set; }
        public string tsbKind { get; set; }
        public short tsbOldYear { get; set; }
        public int tsbOldApplyNo { get; set; }
        public int tsbOldApplySeq { get; set; }
        public int tsbOldDecideNo { get; set; }
        public short tsbOldDecideSeq { get; set; }
        public string tsbOldApplyWordNum { get; set; }
        public Nullable<int> tsbNewBgtNo { get; set; }
    }
}
