//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBC_WebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GBCVisaDetailWithAbate
    {
        public string 基金代碼 { get; set; }
        public string PK_會計年度 { get; set; }
        public string PK_動支編號 { get; set; }
        public string PK_種類 { get; set; }
        public string PK_次別 { get; set; }
        public string PK_明細號 { get; set; }
        public string F_科室代碼 { get; set; }
        public string F_用途別代碼 { get; set; }
        public string F_計畫代碼 { get; set; }
        public Nullable<double> F_動支金額 { get; set; }
        public string F_製票日 { get; set; }
        public string F_是否核定 { get; set; }
        public Nullable<double> F_核定金額 { get; set; }
        public string F_核定日期 { get; set; }
        public string F_摘要 { get; set; }
        public string F_受款人 { get; set; }
        public string F_受款人編號 { get; set; }
        public string F_原動支編號 { get; set; }
        public string F_批號 { get; set; }
        public Nullable<double> 實支 { get; set; }
        public Nullable<double> 預付轉正 { get; set; }
        public Nullable<double> 沖抵估列 { get; set; }
        public Nullable<double> 費用 { get; set; }
    }
}
